### ISSUE TITLE
Adding flexbox to your page

### ISSUE THREAD

**Issue by zannain** [leseigfried/prj-rev-bwfs-tea-cozy#1]
When you are designing a page, you want to think about how a page looks when you try resizing your browser window. What you'll notice is that as you make the window smaller the page doesn't look quite how you had designed it initially and this is expected because you have less area to work with. You may have heard the term "mobile-first" or "responsive-design" and these terms refer to the idea that a page looks good whether you are viewing it on a mobile device or a desktop monitor. One suggestion I have for you is to add Flexbox into your page. Flexbox is a newer addition to CSS which tries to make a webpage more responsive. To get started with Flexbox all you have to do is change your main content to `display:flex`.

```css
.container {
 display: flex;
}
```

You can learn more about flexbox [here](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) !

**Comment by leseigfried** [comment]
Hi Zannain,

Thanks so much for your feedback. I'm a bit confused though--my main container was set as display: flex;. Are you referring to the use of flex-grow and flex-shrink in regards to resizing the page according to device type?

Thanks,
Lauren

**Comment by zannain** [comment]
Hey Lauren,

I apologize, you did use Flexbox but when I was testing the responsiveness of the web page by resizing my browser I noticed that the navigation items began to stack up. 

![image](https://user-images.githubusercontent.com/24375741/34753388-a7227d90-f585-11e7-92ef-460263b0ffd3.png)

If you notice the images aren't resizing so you're not getting the responsive design. To give you a better idea of the power behind flex box here's a few CodePen examples that use flexbox.
[Example 1](https://codepen.io/team/css-tricks/pen/EKEYob)
[Example 2](https://codepen.io/dudleystorey/pen/Kgofa)

Another thing you can look into is media queries that allow you to size-specific styles based on certain conditions such as browser size. [W3C](https://www.w3schools.com/css/css_rwd_mediaqueries.asp) has a good introduction to them. 

Hope this helps!

**Comment by zannain** [comment]
Also thought I'd add this since I noticed it after my first review. 

I noticed you wrapped all your images in `div`s and gave them different class names. In programming, there is a concept known as Don't Repeat Yourself because often times when you find yourself repeating code, it's a red flag that you may need to refactor somewhere. In this case, while its great that you are being descriptive, it would save you a lot of time by giving the `div`s a common class name. Here's a generic example 

```css
.div1{
  height: 300px;
  width: 300px;
  padding: 10px;
}

.div2 {
  height: 300px;
  width: 300px;
  padding: 10px;
}

.div2 {
  height: 300px;
  width: 300px;
  padding: 10px;
}

.div3{
  height: 300px;
  width: 300px;
  padding: 10px;
}

.div4 {
  height: 300px;
  width: 300px;
  padding: 10px;
}
```
you could instead 

```html
<div class="div-outer">
    <div class="div-inner">
        <img src="#" />
    </div>
    <div class="div-inner">
        <img src="#" />
    </div>
    <div class="div-inner">
        <img src="#" />
    </div>
</div>
```
and in your CSS stylesheet you only have to write:

```css
.div-inner {
  height: 300px;
  width: 300px;
  padding: 10px;
}
```
and all the elements, in this case, all the elements with the class **div-inner** will get those styles. This reduces the amount of CSS you have written as well as HTML! Remember that use `class`'es when you need to apply the same styles to multiple elements and use `id`'s when you have to apply a unique style to an element. You are not restricted to how many classes an element has, just make sure separate them with spaces however an `id` by definition is unique and an element should only have one. 

You can read more about [DRY here](http://deviq.com/don-t-repeat-yourself/)

https://github.com/leseigfried/prj-rev-bwfs-tea-cozy/blob/master/tea_cozy/Resources/style.css#L109-L142
